import{useEffect,useState}from'react';
import{firebaseConfigured,saveHumanValidation}from'../firebase';
type Props={point:number;period:string;minute:number;amount:number;place:string};
type Decision='accept'|'reject'|'propose';
const money=(value:number)=>new Intl.NumberFormat('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0}).format(value);
export function HumanFeedback({point,period,minute,amount,place}:Props){
  const[decision,setDecision]=useState<Decision>();const[proposal,setProposal]=useState('');const[confidence,setConfidence]=useState(0);const[status,setStatus]=useState<'idle'|'sending'|'sent'|'queued'|'error'>('idle');const[errorDetail,setErrorDetail]=useState('');
  useEffect(()=>{setDecision(undefined);setProposal('');setConfidence(0);setStatus('idle')},[point,period,minute,amount]);
  const responseAmount=decision==='accept'?amount:decision==='reject'?0:Number(proposal);const valid=Boolean(decision&&confidence&&Number.isFinite(responseAmount)&&responseAmount>=0&&(decision!=='propose'||proposal!==''));
  async function submit(){if(!valid||!decision)return;setStatus('sending');setErrorDetail('');const entry={point,period,minute,decision,predicted_amount:amount,response_amount:responseAmount,confidence,place};try{if(firebaseConfigured){await saveHumanValidation(entry);setStatus('sent')}else{const previous=JSON.parse(localStorage.getItem('ecosonic_human_feedback_pending')||'[]');localStorage.setItem('ecosonic_human_feedback_pending',JSON.stringify([...previous,{...entry,created_at:new Date().toISOString()}]));setStatus('queued')}}catch(error){console.error('No se pudo guardar la validacion en Firebase',error);const code=typeof error==='object'&&error&&'code'in error?String(error.code):'';setErrorDetail(code==='permission-denied'?'Firestore rechazó el registro. Verifica que las reglas estén publicadas en el proyecto ecosonic-c2128.':code==='unavailable'?'Firebase no está disponible en este momento. Revisa tu conexión e inténtalo otra vez.':code?`Firebase respondió: ${code}.`:'No se pudo conectar con Firebase. Revisa la consola del navegador.');setStatus('error')}}
  return <section className="humanLoop" id="evaluar-modelo"><div className="humanLoopIntro"><small>HUMAN-IN-THE-LOOP</small><h3>¿Quieres ayudarnos a evaluar el modelo?</h3><p>Después de observar la evidencia de <b>{place}</b>, indícanos si esta valoración representa lo que aportarías mensualmente.</p></div><div className="humanOffer"><span>El modelo estima un aporte mensual de</span><strong>{money(amount)}</strong><p>para apoyar acciones de conservación y mejoramiento ambiental y acústico del sector.</p></div>
  {status==='sent'||status==='queued'?<div className="feedbackThanks"><strong>{status==='sent'?'Evaluación registrada':'Evaluación guardada en este dispositivo'}</strong><span>{status==='sent'?`Tu respuesta quedó almacenada en la base de datos para el punto ${String(point).padStart(2,'0')}, ${period}, minuto ${minute}, sin recopilar datos personales.`:'Firebase todavía no está configurado. La respuesta quedó pendiente localmente y aún no fue enviada a la base de datos.'}</span></div>:<><div className="decisionGroup" aria-label="Respuesta sobre el valor estimado"><button className={decision==='accept'?'selected':undefined} onClick={()=>setDecision('accept')}>Sí, confirmo ese valor</button><button className={decision==='reject'?'selected reject':undefined} onClick={()=>setDecision('reject')}>No aportaría</button><button className={decision==='propose'?'selected propose':undefined} onClick={()=>setDecision('propose')}>Propondría otro monto</button></div>{decision==='propose'&&<label className="proposalField">Monto mensual que propondrías (COP)<input type="number" min="0" max="10000000" step="100" value={proposal} onChange={e=>setProposal(e.target.value)} placeholder="Ejemplo: 3000"/></label>}<fieldset className="confidenceScale"><legend>¿Qué tan seguro(a) estás de tu respuesta?</legend>{['Nada seguro','Poco seguro','Moderadamente seguro','Seguro','Muy seguro'].map((label,i)=><label key={label}><input type="radio" name="feedback-confidence" checked={confidence===i+1} onChange={()=>setConfidence(i+1)}/><b>{i+1}</b><span>{label}</span></label>)}</fieldset><div className="feedbackSubmit"><p>Esta es una valoración hipotética para fines de investigación; no constituye un cobro ni una donación.</p><button disabled={!valid||status==='sending'} onClick={submit}>{status==='sending'?'Guardando…':'Enviar evaluación'}</button>{status==='error'&&<span>No fue posible guardar. Inténtalo nuevamente.</span>}</div></>}
  </section>}
