import{NavLink,Route,Routes,useLocation}from'react-router-dom';import{Menu,X,ArrowRight,Upload,AudioWaveform,ScanLine,Users,MapPinned}from'lucide-react';import{useEffect,useState}from'react';import Home from'./pages/Home';import Model from'./pages/Model';import Maps from'./pages/Maps';import Explorer from'./pages/Explorer';import Valuation from'./pages/Valuation';import Data from'./pages/Data';
const links=[['/','Inicio'],['/modelo','Modelo'],['/mapas','Mapas'],['/explorador','Explorador'],['/valoracion','Valorar'],['/datos','Datos']];
export function Header(){const[open,setOpen]=useState(false);return <header><div className="wrap nav"><NavLink className="brand" to="/"><i>◉</i><span>ECOSONIC<small>POPAYÁN</small></span></NavLink><button className="menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><nav className={open?'open':''}>{links.map(([to,label])=><NavLink key={to} to={to} onClick={()=>setOpen(false)}>{label}</NavLink>)}</nav></div></header>}
export function Footer(){return <footer><div className="wrap foot"><div><strong>EcoSonic Popayán</strong><span>Paisaje sonoro e inteligencia ambiental</span></div><div>Elaborado por Karen Méndez y Angiee Argote<br/>Popayán · Colombia · 2026</div></div></footer>}
export function PageHero({kicker,title,text}:{kicker:string;title:string;text:string}){return <section className="pageHero"><div className="wrap"><div className="kicker">{kicker}</div><h1>{title}</h1><p>{text}</p></div></section>}
export function Bars({data,audio=false}:{data:{label:string;value:number|null}[];audio?:boolean}){return <div className="hbars">{data.map(x=><div className="hbar" key={x.label}><span>{x.label}</span><div className="barTrack"><i className={audio?'audio':''} style={{width:`${Math.max(0,Math.min(100,x.value||0))}%`}}/></div><b>{x.value==null?'—':`${x.value.toFixed(1)}%`}</b></div>)}</div>}
export const Icons={ArrowRight,Upload,AudioWaveform,ScanLine,Users,MapPinned};
function ScrollManager(){const{pathname,hash}=useLocation();useEffect(()=>{if(!hash)window.scrollTo({top:0,left:0,behavior:'auto'})},[pathname,hash]);return null}
export default function App(){return <><ScrollManager/><Header/><main className="pageEnter"><Routes><Route path="/" element={<Home/>}/><Route path="/modelo" element={<Model/>}/><Route path="/mapas" element={<Maps/>}/><Route path="/explorador" element={<Explorer/>}/><Route path="/valoracion" element={<Valuation/>}/><Route path="/datos" element={<Data/>}/><Route path="*" element={<Home/>}/></Routes></main><Footer/></>}
